name: Build and Publish
on:
  push:
    # Disabled because it seems not reliable to fetch the jar from Github
    # during Ansible deployment from the internal machine network.
    tags:
      - DISABLEDpublish
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build
        run: ./gradlew bootJar
      - name: Test
        run: ./gradlew -Pcovxml=true test
      #- name: Report
      #  run: ./gradlew -Pcovxml=true jacocoTestReport
      #- name: Code coverage
      #  uses: codecov/codecov-action@v1
      #  with:
      #    file: ./build/reports/jacoco/test/jacocoTestReport.xml
      #    fail_ci_if_error: true
      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
